#Config file for the CogWorks plugin.

#Determins the current lang file.
#Keys: https://raw.githubusercontent.com/Mapty231/CogWorks/master/langFiles/0.3/avaiableLangFiles
lang: eng


#Displays stack trace to help with debugging.
#Turn this on before reporting a bug.
#This will be enabled by default until release.
showErrorTrace: true

#On join send op players the amount of errors that have happened with this plugin since last reload/restart.
showOpErrorSummary: true

#Will attempt to automatically install any missing dependencies for other plugins on start up.
#If you have a connection that is slow or bandwidth limited it is recommended to turn off this option.
ADR: true