name: FileManager
version: '${version}'
main: me.tye.filemanager.FileManager
api-version: '1.20'
load: STARTUP

commands:
  plugin:
    usage: /<command> <install/remove> <install:pluginName/Url remove:pluginName>
    description: The base command for installing or removing plugins from the server.
    permission: plugin
  file:
    usage: /<command>
    description: The command allows the user to navigate around the file system and to edit files.
    permission: file

permissions:

  fileman.plugin.install:
    default: op
  fileman.plugin.remove:
    default: op

  fileman.file.nav:
    default: op
  fileman.file.read:
    default: op
  fileman.file.edit:
    default: op
  fileman.file.mk:
    default: op
  fileman.file.rm:
    default: op