name: CogWorks
version: '${version}'
main: me.tye.cogworks.CogWorks
api-version: '1.17'
load: STARTUP

commands:
  plugin:
    usage: /<command> <install/remove/browse> <install:pluginName/Url remove:pluginName>
    description: The base command for installing or removing plugins from the server.
    permission: plugin
  file:
    usage: /<command>
    description: The command allows the user to navigate around the file system and to edit, create, & delete files.
    permission: file

permissions:

  cogworks:
    plugin:
      ins:
        modrinth:
          default: op
        gen:
          default: op
      rm:
        default: op
      reload:
        default: op

    file:
      nav:
        default: op
      read:
        default: op
      edit:
        default: op
      mk:
        default: op
      rm:
        default: op