name: CogWorks
version: '${version}'
main: me.tye.cogworks.CogWorks
api-version: '1.20'
load: STARTUP

commands:
  plugin:
    usage: /<command> <install/remove/browse> <install:pluginName/Url remove:pluginName>
    description: The base command for installing or removing plugins from the server.
    permission: plugin
  file:
    usage: /<command>
    description: The command allows the user to navigate around the file system and to edit files.
    permission: file

permissions:

  cogworks.plugin.ins:
    default: op
  cogworks.plugin.rm:
    default: op

  cogworks.file.nav:
    default: op
  cogworks.file.read:
    default: op
  cogworks.file.edit:
    default: op
  cogworks.file.mk:
    default: op
  cogworks.file.rm:
    default: op